export const data = [
    {
        id: 1,
        imgSrc: 'https://www.soundandvision.com/images/819viziom.promo_.jpg',
        type: 'TV',
        title: 'VIZIO P659-G1',
        description: 'VIZIO - 65" Class P-Series Quantum Series LED 4K UHD SmartCast TV',
        countLeft: '200',
        raised: '5000',
        raisedPercentage: '10',
        daysLeft: '32',
        price: '$1000',
    },
    {
        id: 2,
        imgSrc: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6334/6334012_sd.jpg',
        type: 'TV',
        title: 'Lg Led TV 43 inch',
        description: 'LG - 43" Class LED HD Smart webOS TV',
        countLeft: '76',
        raised: '14000',
        raisedPercentage: '25',
        daysLeft: '30',
        price: '$259.99',
    },
    {
        id: 3,
        imgSrc: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6436/6436833_sd.jpg;maxHeight=640;maxWidth=550',
        type: 'Laptop',
        title: 'ASUS ZenBook S',
        description: 'ASUS - ZenBook S 13.9" Touch-Screen Laptop - Intel Core i7 - 16GB Memory - 1TB Solid State Drive - Jade Black',
        countLeft: '54',
        raised: '46000',
        raisedPercentage: '46',
        daysLeft: '132',
        price: '$1699.99',
    },
    {
        id: 4,
        imgSrc: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6406/6406871_sd.jpg;maxHeight=650;maxWidth=550',
        type: 'Laptop',
        title: 'Lenovo Legion 5',
        description: 'Lenovo - Legion 5 Gaming Laptop 15.6" - Intel Core i7 - 8GB Memory - NVIDIA GeForce GTX 1650 Ti - 256GB SSD - Phantom Black',
        countLeft: '100',
        raised: '2000',
        raisedPercentage: '2',
        daysLeft: '182',
        price: '$969.99',
    },
    {
        id: 5,
        imgSrc: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6419/6419696_sd.jpg',
        type: 'Laptop',
        title: 'Dell G7 15 Gaming Laptop',
        description: 'Dell - G7 15.6" 4K Gaming Laptop - OLED - Intel Core i7 - 16GB Memory - NVIDIA GEFORCE RTX 2070MQ - 1TB SSD - 4-Zone RGB - Black',
        countLeft: '10',
        raised: '310000',
        raisedPercentage: '92',
        daysLeft: '5',
        price: '$1649.99',
    },
];
